import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { db } from '@/firebase/client';
import { doc, getDoc } from 'firebase/firestore';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [name, setName] = useState('');

  function loadName(): void {
    if (!name) {
      getDoc(doc(db, 'user', 'doc1'))
        .then((d) => setName(d.data()?.name))
        .catch((e) => console.log('e', e));
    }
  }

  return (
    <>
      <Head>
        <title>{`Old Deploy ${name && `| ${name}`}`}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p className={inter.className}>{name}</p>
        </div>
        <div className={styles.center} onClick={loadName}>
          <Image
            className={styles.logo}
            src='/next.svg'
            alt='Next.js Logo'
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src='/thirteen.svg'
              alt='13'
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
      </main>
    </>
  );
}

